{"topicSections":[{"identifiers":["doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/DefaultMessagingFactory","doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/DefaultMessagingSwiftUIFactory","doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/PushNotifications","doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/UserColors"],"generated":true,"title":"Classes","anchor":"Classes"},{"identifiers":["doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/NativeMessagingSDKVersionNumber","doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/NativeMessagingSDKVersionString"],"generated":true,"title":"Variables","anchor":"Variables"},{"identifiers":["doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/PushResponsibility"],"generated":true,"title":"Enumerations","anchor":"Enumerations"},{"identifiers":["doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/CoreFoundation","doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/UIKit"],"generated":true,"title":"Extended Modules","anchor":"Extended-Modules"}],"sections":[],"metadata":{"role":"collection","symbolKind":"module","roleHeading":"Framework","title":"ZendeskSDKMessaging","modules":[{"name":"ZendeskSDKMessaging"}],"externalID":"ZendeskSDKMessaging"},"variants":[{"paths":["\/documentation\/zendesksdkmessaging"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdkmessaging"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging"},"hierarchy":{"paths":[[]]},"references":{"doc://com.zendesk.Messaging/documentation/ZendeskSDKMessaging/CoreFoundation":{"abstract":[],"role":"collection","url":"\/documentation\/zendesksdkmessaging\/corefoundation","identifier":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/CoreFoundation","title":"CoreFoundation","type":"topic","kind":"symbol"},"doc://com.zendesk.Messaging/documentation/ZendeskSDKMessaging/UserColors":{"url":"\/documentation\/zendesksdkmessaging\/usercolors","role":"symbol","title":"UserColors","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UserColors"}],"abstract":[{"type":"text","text":"Model that contains the colors provided by the user to be used in the SDK."}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/UserColors","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserColors"}]},"doc://com.zendesk.Messaging/documentation/ZendeskSDKMessaging/NativeMessagingSDKVersionString":{"role":"symbol","abstract":[{"text":"Project version string for NativeMessagingSDK.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/NativeMessagingSDKVersionString","url":"\/documentation\/zendesksdkmessaging\/nativemessagingsdkversionstring","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NativeMessagingSDKVersionString","kind":"identifier"},{"text":": <<error type>>","kind":"text"}],"navigatorTitle":[{"text":"NativeMessagingSDKVersionString","kind":"identifier"}],"type":"topic","title":"NativeMessagingSDKVersionString"},"doc://com.zendesk.Messaging/documentation/ZendeskSDKMessaging/DefaultMessagingSwiftUIFactory":{"abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DefaultMessagingSwiftUIFactory"}],"type":"topic","url":"\/documentation\/zendesksdkmessaging\/defaultmessagingswiftuifactory","identifier":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/DefaultMessagingSwiftUIFactory","kind":"symbol","role":"symbol","title":"DefaultMessagingSwiftUIFactory","navigatorTitle":[{"kind":"identifier","text":"DefaultMessagingSwiftUIFactory"}]},"doc://com.zendesk.Messaging/documentation/ZendeskSDKMessaging/NativeMessagingSDKVersionNumber":{"type":"topic","abstract":[{"type":"text","text":"Project version number for NativeMessagingSDK."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"NativeMessagingSDKVersionNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"title":"NativeMessagingSDKVersionNumber","role":"symbol","identifier":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/NativeMessagingSDKVersionNumber","navigatorTitle":[{"kind":"identifier","text":"NativeMessagingSDKVersionNumber"}],"kind":"symbol","url":"\/documentation\/zendesksdkmessaging\/nativemessagingsdkversionnumber"},"doc://com.zendesk.Messaging/documentation/ZendeskSDKMessaging/UIKit":{"identifier":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/UIKit","title":"UIKit","type":"topic","role":"collection","url":"\/documentation\/zendesksdkmessaging\/uikit","abstract":[],"kind":"symbol"},"doc://com.zendesk.Messaging/documentation/ZendeskSDKMessaging/PushNotifications":{"title":"PushNotifications","type":"topic","navigatorTitle":[{"text":"PushNotifications","kind":"identifier"}],"abstract":[{"text":"The entry point to execute push notification related SDK actions.","type":"text"},{"text":" ","type":"text"},{"text":"Register device token with ","type":"text"},{"code":"PushNotifications.updatePushNotificationToken(:)","type":"codeVoice"},{"text":".","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PushNotifications","kind":"identifier"}],"url":"\/documentation\/zendesksdkmessaging\/pushnotifications","identifier":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/PushNotifications","kind":"symbol","role":"symbol"},"doc://com.zendesk.Messaging/documentation/ZendeskSDKMessaging":{"role":"collection","abstract":[],"identifier":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging","title":"ZendeskSDKMessaging","url":"\/documentation\/zendesksdkmessaging","kind":"symbol","type":"topic"},"doc://com.zendesk.Messaging/documentation/ZendeskSDKMessaging/PushResponsibility":{"url":"\/documentation\/zendesksdkmessaging\/pushresponsibility","role":"symbol","abstract":[{"text":"Represents whether a push notification payload belongs to ","type":"text"},{"code":"Messaging","type":"codeVoice"},{"text":",","type":"text"},{"text":" ","type":"text"},{"text":"and if the SDK is in a state in which the notification should be displayed.","type":"text"}],"type":"topic","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PushResponsibility","kind":"identifier"}],"navigatorTitle":[{"text":"PushResponsibility","kind":"identifier"}],"title":"PushResponsibility","identifier":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/PushResponsibility"},"doc://com.zendesk.Messaging/documentation/ZendeskSDKMessaging/DefaultMessagingFactory":{"type":"topic","navigatorTitle":[{"text":"DefaultMessagingFactory","kind":"identifier"}],"url":"\/documentation\/zendesksdkmessaging\/defaultmessagingfactory","abstract":[],"title":"DefaultMessagingFactory","kind":"symbol","identifier":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/DefaultMessagingFactory","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DefaultMessagingFactory"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/topicSections","op":"replace","value":[{"title":"Classes","anchor":"Classes","identifiers":["doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/DefaultMessagingFactory","doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/PushNotifications","doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/UserColors"],"generated":true},{"title":"Variables","anchor":"Variables","identifiers":["doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/NativeMessagingSDKVersionNumber","doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/NativeMessagingSDKVersionString"],"generated":true},{"title":"Enumerations","anchor":"Enumerations","identifiers":["doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/PushResponsibility"],"generated":true}]},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1UserColors\/title","op":"replace","value":"ZDKUserColors"},{"path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1UserColors\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKUserColors"}]},{"path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1UserColors\/navigatorTitle","op":"replace","value":[{"text":"ZDKUserColors","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1NativeMessagingSDKVersionString\/title","value":"NativeMessagingSDKVersionString"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1NativeMessagingSDKVersionString\/fragments","value":[{"text":"NativeMessagingSDKVersionString","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1NativeMessagingSDKVersionNumber\/title","value":"NativeMessagingSDKVersionNumber"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1NativeMessagingSDKVersionNumber\/fragments","value":[{"kind":"identifier","text":"NativeMessagingSDKVersionNumber"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1PushNotifications\/title","value":"ZDKPushNotifications"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1PushNotifications\/fragments","value":[{"kind":"identifier","text":"ZDKPushNotifications"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1PushNotifications\/navigatorTitle","value":[{"text":"ZDKPushNotifications","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1PushResponsibility\/title","value":"ZDKPushResponsibility"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1PushResponsibility\/fragments","value":[{"text":"ZDKPushResponsibility","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1PushResponsibility\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKPushResponsibility"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1DefaultMessagingFactory\/title","value":"ZDKDefaultMessagingFactory"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1DefaultMessagingFactory\/fragments","value":[{"kind":"identifier","text":"ZDKDefaultMessagingFactory"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1DefaultMessagingFactory\/navigatorTitle","value":[{"text":"ZDKDefaultMessagingFactory","kind":"identifier"}]}]}]}