{"metadata":{"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createMessaging","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MessagingFactoryParameters","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKMessagingFactoryParameters"},{"text":") -> ","kind":"text"},{"text":"Messaging","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKMessaging"}],"title":"createMessaging(with:)","symbolKind":"method","navigatorTitle":[{"text":"createMessagingWith:","kind":"identifier"}],"role":"symbol","modules":[{"name":"ZendeskSDKMessaging"}],"externalID":"c:@M@ZendeskSDKMessaging@objc(cs)ZDKDefaultMessagingFactory(im)createMessagingWith:"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkmessaging\/defaultmessagingfactory\/createmessaging(with:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkmessaging\/defaultmessagingfactory\/createmessaging(with:)"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createMessaging","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"parameters","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"MessagingFactoryParameters","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKMessagingFactoryParameters","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Messaging","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKMessaging","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/DefaultMessagingFactory\/createMessaging(with:)"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging","doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/DefaultMessagingFactory"]]},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"MessagingFactory.createMessaging(with:)","type":"codeVoice"},{"text":".","type":"text"}],"sections":[],"kind":"symbol","references":{"doc://com.zendesk.Messaging/documentation/ZendeskSDKMessaging":{"title":"ZendeskSDKMessaging","abstract":[],"kind":"symbol","type":"topic","role":"collection","identifier":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging","url":"\/documentation\/zendesksdkmessaging"},"doc://com.zendesk.Messaging/documentation/ZendeskSDKMessaging/DefaultMessagingFactory":{"title":"DefaultMessagingFactory","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/DefaultMessagingFactory","type":"topic","url":"\/documentation\/zendesksdkmessaging\/defaultmessagingfactory","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DefaultMessagingFactory"}],"navigatorTitle":[{"kind":"identifier","text":"DefaultMessagingFactory"}]},"doc://com.zendesk.Messaging/documentation/ZendeskSDKMessaging/DefaultMessagingFactory/createMessaging(with:)":{"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createMessaging","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MessagingFactoryParameters","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKMessagingFactoryParameters","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Messaging","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKMessaging","kind":"typeIdentifier"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/DefaultMessagingFactory\/createMessaging(with:)","abstract":[],"navigatorTitle":[{"text":"createMessagingWith:","kind":"identifier"}],"role":"symbol","title":"createMessaging(with:)","url":"\/documentation\/zendesksdkmessaging\/defaultmessagingfactory\/createmessaging(with:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"createMessagingWith:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"createMessagingWith:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"ZDKMessaging","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKMessaging","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"createMessagingWith:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ZDKMessagingFactoryParameters","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKMessagingFactoryParameters","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"parameters","kind":"internalParam"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"ZDKDefaultMessagingFactory","path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1DefaultMessagingFactory\/title"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKDefaultMessagingFactory"}],"path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1DefaultMessagingFactory\/fragments"},{"value":[{"kind":"identifier","text":"ZDKDefaultMessagingFactory"}],"path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1DefaultMessagingFactory\/navigatorTitle","op":"replace"},{"value":"createMessagingWith:","path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1DefaultMessagingFactory~1createMessaging(with:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"createMessagingWith:"}],"path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1DefaultMessagingFactory~1createMessaging(with:)\/fragments","op":"replace"}]}]}