{"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/zendesksdkmessaging\/defaultmessagingfactory\/init(userlightcolors:userdarkcolors:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdkmessaging\/defaultmessagingfactory\/init(userlightcolors:userdarkcolors:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"abstract":[{"text":"Default initialization of ","type":"text"},{"type":"codeVoice","code":"MessagingFactory"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"userLightColors","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/UserColors","text":"UserColors","preciseIdentifier":"c:@M@ZendeskSDKMessaging@objc(cs)ZDKUserColors","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"userDarkColors","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/UserColors","text":"UserColors","preciseIdentifier":"c:@M@ZendeskSDKMessaging@objc(cs)ZDKUserColors","kind":"typeIdentifier"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"userLightColors","content":[{"inlineContent":[{"type":"text","text":"Object that contains the light colors provided by the user to be used in the SDK."}],"type":"paragraph"}]},{"name":"userDarkColors","content":[{"type":"paragraph","inlineContent":[{"text":"Object that contains the dark colors provided by the user to be used in the SDK.","type":"text"}]}]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging","doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/DefaultMessagingFactory"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/DefaultMessagingFactory\/init(userLightColors:userDarkColors:)"},"metadata":{"roleHeading":"Initializer","title":"init(userLightColors:userDarkColors:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"userLightColors","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDKMessaging@objc(cs)ZDKUserColors","text":"UserColors","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"userDarkColors","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDKMessaging@objc(cs)ZDKUserColors","text":"UserColors","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","externalID":"c:@M@ZendeskSDKMessaging@objc(cs)ZDKDefaultMessagingFactory(im)initWithUserLightColors:userDarkColors:","modules":[{"name":"ZendeskSDKMessaging"}],"symbolKind":"init","navigatorTitle":[{"text":"initWithUserLightColors:userDarkColors:","kind":"identifier"}]},"references":{"doc://com.zendesk.Messaging/documentation/ZendeskSDKMessaging/DefaultMessagingFactory":{"kind":"symbol","title":"DefaultMessagingFactory","abstract":[],"navigatorTitle":[{"text":"DefaultMessagingFactory","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/zendesksdkmessaging\/defaultmessagingfactory","identifier":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/DefaultMessagingFactory","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DefaultMessagingFactory","kind":"identifier"}]},"doc://com.zendesk.Messaging/documentation/ZendeskSDKMessaging/DefaultMessagingFactory/init(userLightColors:userDarkColors:)":{"url":"\/documentation\/zendesksdkmessaging\/defaultmessagingfactory\/init(userlightcolors:userdarkcolors:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithUserLightColors:userDarkColors:"}],"title":"init(userLightColors:userDarkColors:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"userLightColors","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDKMessaging@objc(cs)ZDKUserColors","text":"UserColors","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"userDarkColors","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDKMessaging@objc(cs)ZDKUserColors","text":"UserColors","kind":"typeIdentifier"},{"kind":"text","text":")"}],"abstract":[{"text":"Default initialization of ","type":"text"},{"code":"MessagingFactory","type":"codeVoice"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/DefaultMessagingFactory\/init(userLightColors:userDarkColors:)"},"doc://com.zendesk.Messaging/documentation/ZendeskSDKMessaging":{"title":"ZendeskSDKMessaging","type":"topic","url":"\/documentation\/zendesksdkmessaging","role":"collection","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging"},"doc://com.zendesk.Messaging/documentation/ZendeskSDKMessaging/UserColors":{"title":"UserColors","role":"symbol","kind":"symbol","abstract":[{"text":"Model that contains the colors provided by the user to be used in the SDK.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserColors"}],"navigatorTitle":[{"kind":"identifier","text":"UserColors"}],"identifier":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/UserColors","type":"topic","url":"\/documentation\/zendesksdkmessaging\/usercolors"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"initWithUserLightColors:userDarkColors:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithUserLightColors:userDarkColors:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithUserLightColors:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ZendeskSDKMessaging@objc(cs)ZDKUserColors","kind":"typeIdentifier","text":"ZDKUserColors","identifier":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/UserColors"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"userLightColors"},{"kind":"text","text":" "},{"kind":"identifier","text":"userDarkColors:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ZendeskSDKMessaging@objc(cs)ZDKUserColors","kind":"typeIdentifier","text":"ZDKUserColors","identifier":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/UserColors"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"userDarkColors"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"userLightColors","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Object that contains the light colors provided by the user to be used in the SDK."}]}]},{"name":"userDarkColors","content":[{"type":"paragraph","inlineContent":[{"text":"Object that contains the dark colors provided by the user to be used in the SDK.","type":"text"}]}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1DefaultMessagingFactory\/title","value":"ZDKDefaultMessagingFactory","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1DefaultMessagingFactory\/fragments","value":[{"kind":"identifier","text":"ZDKDefaultMessagingFactory"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1DefaultMessagingFactory\/navigatorTitle","value":[{"text":"ZDKDefaultMessagingFactory","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1DefaultMessagingFactory~1init(userLightColors:userDarkColors:)\/title","value":"initWithUserLightColors:userDarkColors:","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1DefaultMessagingFactory~1init(userLightColors:userDarkColors:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithUserLightColors:userDarkColors:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1UserColors\/title","value":"ZDKUserColors","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1UserColors\/fragments","value":[{"kind":"identifier","text":"ZDKUserColors"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1UserColors\/navigatorTitle","value":[{"text":"ZDKUserColors","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}