{"sections":[],"metadata":{"role":"symbol","roleHeading":"Class","externalID":"c:@M@ZendeskSDKMessaging@objc(cs)ZDKDefaultMessagingFactory","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DefaultMessagingFactory","kind":"identifier"}],"navigatorTitle":[{"text":"DefaultMessagingFactory","kind":"identifier"}],"modules":[{"name":"ZendeskSDKMessaging"}],"title":"DefaultMessagingFactory","symbolKind":"class"},"variants":[{"paths":["\/documentation\/zendesksdkmessaging\/defaultmessagingfactory"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdkmessaging\/defaultmessagingfactory"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(ZDKDefaultMessagingFactory) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DefaultMessagingFactory"}]}]}],"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.zendesk.Messaging\/objc(cs)NSObject"]},{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.zendesk.Messaging\/objc(pl)NSObject","doc:\/\/com.zendesk.Messaging\/s7CVarArgP","doc:\/\/com.zendesk.Messaging\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.Messaging\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.Messaging\/SQ","doc:\/\/com.zendesk.Messaging\/SH","doc:\/\/com.zendesk.Messaging\/@M@ZendeskSDK@objc(pl)MessagingFactory"]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging"]]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"generated":true,"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/DefaultMessagingFactory\/init()","doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/DefaultMessagingFactory\/init(userLightColors:)","doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/DefaultMessagingFactory\/init(userLightColors:userDarkColors:)"]},{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/DefaultMessagingFactory\/createMessaging(with:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/DefaultMessagingFactory"},"references":{"doc://com.zendesk.Messaging/documentation/ZendeskSDKMessaging":{"title":"ZendeskSDKMessaging","abstract":[],"kind":"symbol","type":"topic","role":"collection","identifier":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging","url":"\/documentation\/zendesksdkmessaging"},"doc://com.zendesk.Messaging/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.zendesk.Messaging\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.zendesk.Messaging/objc(pl)NSObject":{"identifier":"doc:\/\/com.zendesk.Messaging\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.zendesk.Messaging/objc(cs)NSObject":{"identifier":"doc:\/\/com.zendesk.Messaging\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.zendesk.Messaging/SH":{"identifier":"doc:\/\/com.zendesk.Messaging\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.zendesk.Messaging/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.zendesk.Messaging\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.zendesk.Messaging/SQ":{"identifier":"doc:\/\/com.zendesk.Messaging\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.zendesk.Messaging/documentation/ZendeskSDKMessaging/DefaultMessagingFactory":{"title":"DefaultMessagingFactory","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/DefaultMessagingFactory","type":"topic","url":"\/documentation\/zendesksdkmessaging\/defaultmessagingfactory","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DefaultMessagingFactory"}],"navigatorTitle":[{"kind":"identifier","text":"DefaultMessagingFactory"}]},"doc://com.zendesk.Messaging/documentation/ZendeskSDKMessaging/DefaultMessagingFactory/init(userLightColors:userDarkColors:)":{"abstract":[{"text":"Default initialization of ","type":"text"},{"code":"MessagingFactory","type":"codeVoice"}],"url":"\/documentation\/zendesksdkmessaging\/defaultmessagingfactory\/init(userlightcolors:userdarkcolors:)","role":"symbol","navigatorTitle":[{"text":"initWithUserLightColors:userDarkColors:","kind":"identifier"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"userLightColors","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UserColors","preciseIdentifier":"c:@M@ZendeskSDKMessaging@objc(cs)ZDKUserColors","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"userDarkColors","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UserColors","preciseIdentifier":"c:@M@ZendeskSDKMessaging@objc(cs)ZDKUserColors","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"init(userLightColors:userDarkColors:)","kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/DefaultMessagingFactory\/init(userLightColors:userDarkColors:)"},"doc://com.zendesk.Messaging/documentation/ZendeskSDKMessaging/DefaultMessagingFactory/init()":{"abstract":[],"url":"\/documentation\/zendesksdkmessaging\/defaultmessagingfactory\/init()","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"init"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"kind":"symbol","title":"init()","type":"topic","identifier":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/DefaultMessagingFactory\/init()"},"doc://com.zendesk.Messaging/@M@ZendeskSDK@objc(pl)MessagingFactory":{"identifier":"doc:\/\/com.zendesk.Messaging\/@M@ZendeskSDK@objc(pl)MessagingFactory","type":"unresolvable","title":"MessagingFactory"},"doc://com.zendesk.Messaging/documentation/ZendeskSDKMessaging/DefaultMessagingFactory/init(userLightColors:)":{"type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"userLightColors"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKMessaging@objc(cs)ZDKUserColors","text":"UserColors"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/DefaultMessagingFactory\/init(userLightColors:)","navigatorTitle":[{"kind":"identifier","text":"initWithUserLightColors:"}],"url":"\/documentation\/zendesksdkmessaging\/defaultmessagingfactory\/init(userlightcolors:)","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Default initialization of "},{"type":"codeVoice","code":"MessagingFactory"}],"title":"init(userLightColors:)"},"doc://com.zendesk.Messaging/documentation/ZendeskSDKMessaging/DefaultMessagingFactory/createMessaging(with:)":{"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createMessaging","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MessagingFactoryParameters","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKMessagingFactoryParameters","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Messaging","preciseIdentifier":"c:@M@ZendeskSDK@objc(cs)ZDKMessaging","kind":"typeIdentifier"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/DefaultMessagingFactory\/createMessaging(with:)","abstract":[],"navigatorTitle":[{"text":"createMessagingWith:","kind":"identifier"}],"role":"symbol","title":"createMessaging(with:)","url":"\/documentation\/zendesksdkmessaging\/defaultmessagingfactory\/createmessaging(with:)"},"doc://com.zendesk.Messaging/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.zendesk.Messaging\/s7CVarArgP"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"value":"ZDKDefaultMessagingFactory","path":"\/metadata\/title","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"ZDKDefaultMessagingFactory","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"ZDKDefaultMessagingFactory","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/DefaultMessagingFactory\/createMessaging(with:)","doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/DefaultMessagingFactory\/init()","doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/DefaultMessagingFactory\/init(userLightColors:)","doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/DefaultMessagingFactory\/init(userLightColors:userDarkColors:)"],"title":"Instance Methods"}],"path":"\/topicSections","op":"replace"},{"value":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.zendesk.Messaging\/objc(cs)NSObject"],"kind":"relationships"},{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.zendesk.Messaging\/@M@ZendeskSDK@objc(pl)MessagingFactory"],"kind":"relationships"}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKDefaultMessagingFactory","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"ZDKDefaultMessagingFactory","path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1DefaultMessagingFactory\/title","op":"replace"},{"value":[{"text":"ZDKDefaultMessagingFactory","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1DefaultMessagingFactory\/fragments","op":"replace"},{"value":[{"text":"ZDKDefaultMessagingFactory","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1DefaultMessagingFactory\/navigatorTitle","op":"replace"},{"value":"initWithUserLightColors:userDarkColors:","path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1DefaultMessagingFactory~1init(userLightColors:userDarkColors:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithUserLightColors:userDarkColors:"}],"path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1DefaultMessagingFactory~1init(userLightColors:userDarkColors:)\/fragments","op":"replace"},{"value":"init","path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1DefaultMessagingFactory~1init()\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1DefaultMessagingFactory~1init()\/fragments","op":"replace"},{"value":"initWithUserLightColors:","path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1DefaultMessagingFactory~1init(userLightColors:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithUserLightColors:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1DefaultMessagingFactory~1init(userLightColors:)\/fragments","op":"replace"},{"value":"createMessagingWith:","path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1DefaultMessagingFactory~1createMessaging(with:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"createMessagingWith:"}],"path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1DefaultMessagingFactory~1createMessaging(with:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}