{"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NativeMessagingSDKVersionNumber","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}]}],"kind":"declarations"}],"abstract":[{"text":"Project version number for NativeMessagingSDK.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkmessaging\/nativemessagingsdkversionnumber"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkmessaging\/nativemessagingsdkversionnumber"]}],"metadata":{"roleHeading":"Global Variable","symbolKind":"var","title":"NativeMessagingSDKVersionNumber","externalID":"c:@NativeMessagingSDKVersionNumber","role":"symbol","modules":[{"name":"ZendeskSDKMessaging"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NativeMessagingSDKVersionNumber","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"NativeMessagingSDKVersionNumber","kind":"identifier"}]},"identifier":{"url":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/NativeMessagingSDKVersionNumber","interfaceLanguage":"swift"},"sections":[],"references":{"doc://com.zendesk.Messaging/documentation/ZendeskSDKMessaging/NativeMessagingSDKVersionNumber":{"title":"NativeMessagingSDKVersionNumber","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NativeMessagingSDKVersionNumber","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"url":"\/documentation\/zendesksdkmessaging\/nativemessagingsdkversionnumber","navigatorTitle":[{"text":"NativeMessagingSDKVersionNumber","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol","abstract":[{"text":"Project version number for NativeMessagingSDK.","type":"text"}],"identifier":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/NativeMessagingSDKVersionNumber"},"doc://com.zendesk.Messaging/documentation/ZendeskSDKMessaging":{"title":"ZendeskSDKMessaging","abstract":[],"kind":"symbol","type":"topic","role":"collection","identifier":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging","url":"\/documentation\/zendesksdkmessaging"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Global Variable","path":"\/metadata\/roleHeading","op":"replace"},{"value":"NativeMessagingSDKVersionNumber","path":"\/metadata\/title","op":"replace"},{"value":"var","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"NativeMessagingSDKVersionNumber"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"preciseIdentifier":"c:d","kind":"typeIdentifier","text":"double"},{"kind":"text","text":" "},{"kind":"identifier","text":"NativeMessagingSDKVersionNumber"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"NativeMessagingSDKVersionNumber","path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1NativeMessagingSDKVersionNumber\/title","op":"replace"},{"value":[{"text":"NativeMessagingSDKVersionNumber","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1NativeMessagingSDKVersionNumber\/fragments","op":"replace"}]}]}