{"identifier":{"url":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/PushNotifications\/shouldBeDisplayed(_:)","interfaceLanguage":"swift"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkmessaging\/pushnotifications\/shouldbedisplayed(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkmessaging\/pushnotifications\/shouldbedisplayed(_:)"]}],"abstract":[{"type":"text","text":"Check if a push notification payload belongs to "},{"type":"codeVoice","code":"Messaging"},{"type":"text","text":" and can be displayed."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"shouldBeDisplayed"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"userInfo"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier","text":"AnyHashable"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]) -> "},{"preciseIdentifier":"c:@M@ZendeskSDKMessaging@E@ZDKPushResponsibility","kind":"typeIdentifier","text":"PushResponsibility","identifier":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/PushResponsibility"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"userInfo","content":[{"inlineContent":[{"text":"The push notification payload.","type":"text"}],"type":"paragraph"}]}]},{"content":[{"text":"Return Value","anchor":"return-value","type":"heading","level":2},{"inlineContent":[{"text":"","type":"text"},{"code":"PushResponsbility","type":"codeVoice"},{"text":" enum indiciating if the push notification should be displayed.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"metadata":{"modules":[{"name":"ZendeskSDKMessaging"}],"externalID":"c:@M@ZendeskSDKMessaging@objc(cs)ZDKPushNotifications(cm)shouldBeDisplayed:","title":"shouldBeDisplayed(_:)","roleHeading":"Type Method","symbolKind":"method","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shouldBeDisplayed","kind":"identifier"},{"text":"([","kind":"text"},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]) -> ","kind":"text"},{"text":"PushResponsibility","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKMessaging@E@ZDKPushResponsibility"}],"navigatorTitle":[{"text":"shouldBeDisplayed:","kind":"identifier"}],"role":"symbol"},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging","doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/PushNotifications"]]},"kind":"symbol","references":{"doc://com.zendesk.Messaging/documentation/ZendeskSDKMessaging/PushResponsibility":{"kind":"symbol","title":"PushResponsibility","role":"symbol","abstract":[{"type":"text","text":"Represents whether a push notification payload belongs to "},{"code":"Messaging","type":"codeVoice"},{"type":"text","text":","},{"type":"text","text":" "},{"type":"text","text":"and if the SDK is in a state in which the notification should be displayed."}],"navigatorTitle":[{"text":"PushResponsibility","kind":"identifier"}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PushResponsibility","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/PushResponsibility","url":"\/documentation\/zendesksdkmessaging\/pushresponsibility"},"doc://com.zendesk.Messaging/documentation/ZendeskSDKMessaging/PushNotifications":{"url":"\/documentation\/zendesksdkmessaging\/pushnotifications","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushNotifications"}],"navigatorTitle":[{"kind":"identifier","text":"PushNotifications"}],"title":"PushNotifications","abstract":[{"text":"The entry point to execute push notification related SDK actions.","type":"text"},{"text":" ","type":"text"},{"text":"Register device token with ","type":"text"},{"code":"PushNotifications.updatePushNotificationToken(:)","type":"codeVoice"},{"text":".","type":"text"}],"identifier":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/PushNotifications","type":"topic","role":"symbol"},"doc://com.zendesk.Messaging/documentation/ZendeskSDKMessaging/PushNotifications/shouldBeDisplayed(_:)":{"identifier":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/PushNotifications\/shouldBeDisplayed(_:)","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shouldBeDisplayed","kind":"identifier"},{"text":"([","kind":"text"},{"text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]) -> ","kind":"text"},{"text":"PushResponsibility","preciseIdentifier":"c:@M@ZendeskSDKMessaging@E@ZDKPushResponsibility","kind":"typeIdentifier"}],"url":"\/documentation\/zendesksdkmessaging\/pushnotifications\/shouldbedisplayed(_:)","role":"symbol","title":"shouldBeDisplayed(_:)","kind":"symbol","navigatorTitle":[{"text":"shouldBeDisplayed:","kind":"identifier"}],"abstract":[{"type":"text","text":"Check if a push notification payload belongs to "},{"code":"Messaging","type":"codeVoice"},{"type":"text","text":" and can be displayed."}]},"doc://com.zendesk.Messaging/documentation/ZendeskSDKMessaging":{"url":"\/documentation\/zendesksdkmessaging","role":"collection","kind":"symbol","identifier":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging","title":"ZendeskSDKMessaging","abstract":[],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"path":"\/metadata\/title","op":"replace","value":"shouldBeDisplayed:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"shouldBeDisplayed:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/PushResponsibility","text":"ZDKPushResponsibility","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKMessaging@E@ZDKPushResponsibility"},{"text":") ","kind":"text"},{"text":"shouldBeDisplayed:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSDictionary","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDictionary"},{"text":" *) ","kind":"text"},{"text":"userInfo","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"name":"userInfo","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The push notification payload."}]}]}]}},{"path":"\/primaryContentSections\/2","op":"replace","value":{"content":[{"anchor":"return-value","type":"heading","level":2,"text":"Return Value"},{"inlineContent":[{"text":"","type":"text"},{"type":"codeVoice","code":"PushResponsbility"},{"text":" enum indiciating if the push notification should be displayed.","type":"text"}],"type":"paragraph"}],"kind":"content"}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1PushResponsibility\/title","value":"ZDKPushResponsibility"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1PushResponsibility\/fragments","value":[{"kind":"identifier","text":"ZDKPushResponsibility"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1PushResponsibility\/navigatorTitle","value":[{"text":"ZDKPushResponsibility","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1PushNotifications\/title","value":"ZDKPushNotifications"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1PushNotifications\/fragments","value":[{"text":"ZDKPushNotifications","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1PushNotifications\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKPushNotifications"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1PushNotifications~1shouldBeDisplayed(_:)\/title","value":"shouldBeDisplayed:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1PushNotifications~1shouldBeDisplayed(_:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"shouldBeDisplayed:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}