{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkmessaging\/pushresponsibility\/equatable-implementations"]}],"identifier":{"url":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/PushResponsibility\/Equatable-Implementations","interfaceLanguage":"swift"},"metadata":{"roleHeading":"API Collection","title":"Equatable Implementations","role":"collectionGroup","modules":[{"name":"ZendeskSDKMessaging"}]},"topicSections":[{"title":"Operators","generated":true,"identifiers":["doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/PushResponsibility\/!=(_:_:)"],"anchor":"Operators"}],"kind":"article","sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging","doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/PushResponsibility"]]},"references":{"doc://com.zendesk.Messaging/documentation/ZendeskSDKMessaging/PushResponsibility":{"url":"\/documentation\/zendesksdkmessaging\/pushresponsibility","identifier":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/PushResponsibility","kind":"symbol","navigatorTitle":[{"text":"PushResponsibility","kind":"identifier"}],"role":"symbol","title":"PushResponsibility","abstract":[{"text":"Represents whether a push notification payload belongs to ","type":"text"},{"code":"Messaging","type":"codeVoice"},{"text":",","type":"text"},{"text":" ","type":"text"},{"text":"and if the SDK is in a state in which the notification should be displayed.","type":"text"}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PushResponsibility","kind":"identifier"}]},"doc://com.zendesk.Messaging/documentation/ZendeskSDKMessaging":{"title":"ZendeskSDKMessaging","abstract":[],"kind":"symbol","type":"topic","role":"collection","identifier":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging","url":"\/documentation\/zendesksdkmessaging"},"doc://com.zendesk.Messaging/documentation/ZendeskSDKMessaging/PushResponsibility/!=(_:_:)":{"url":"\/documentation\/zendesksdkmessaging\/pushresponsibility\/!=(_:_:)","abstract":[],"type":"topic","title":"!=(_:_:)","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"identifier":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/PushResponsibility\/!=(_:_:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"ZDKPushResponsibility","path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1PushResponsibility\/title","op":"replace"},{"value":[{"kind":"identifier","text":"ZDKPushResponsibility"}],"path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1PushResponsibility\/fragments","op":"replace"},{"value":[{"text":"ZDKPushResponsibility","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1PushResponsibility\/navigatorTitle","op":"replace"}]}]}