{"abstract":[{"type":"text","text":"Model that contains the colors provided by the user to be used in the SDK."}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging"]]},"identifier":{"url":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/UserColors","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(ZDKUserColors) "},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserColors"}],"languages":["swift"]}]}],"sections":[],"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.zendesk.Messaging\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From"},{"kind":"relationships","identifiers":["doc:\/\/com.zendesk.Messaging\/objc(pl)NSObject","doc:\/\/com.zendesk.Messaging\/s7CVarArgP","doc:\/\/com.zendesk.Messaging\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.Messaging\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.Messaging\/SQ","doc:\/\/com.zendesk.Messaging\/SH"],"type":"conformsTo","title":"Conforms To"}],"metadata":{"roleHeading":"Class","role":"symbol","symbolKind":"class","navigatorTitle":[{"kind":"identifier","text":"UserColors"}],"title":"UserColors","modules":[{"name":"ZendeskSDKMessaging"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UserColors"}],"externalID":"c:@M@ZendeskSDKMessaging@objc(cs)ZDKUserColors"},"topicSections":[{"identifiers":["doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/UserColors\/init(onPrimary:onMessage:onAction:)"],"title":"Initializers"}],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkmessaging\/usercolors"]},{"paths":["\/documentation\/zendesksdkmessaging\/usercolors"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.zendesk.Messaging/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.zendesk.Messaging\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.zendesk.Messaging/documentation/ZendeskSDKMessaging":{"title":"ZendeskSDKMessaging","kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/zendesksdkmessaging","identifier":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging","abstract":[]},"doc://com.zendesk.Messaging/SQ":{"identifier":"doc:\/\/com.zendesk.Messaging\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.zendesk.Messaging/objc(pl)NSObject":{"identifier":"doc:\/\/com.zendesk.Messaging\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.zendesk.Messaging/documentation/ZendeskSDKMessaging/UserColors":{"type":"topic","url":"\/documentation\/zendesksdkmessaging\/usercolors","identifier":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/UserColors","abstract":[{"text":"Model that contains the colors provided by the user to be used in the SDK.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UserColors"}],"title":"UserColors","role":"symbol","navigatorTitle":[{"text":"UserColors","kind":"identifier"}]},"doc://com.zendesk.Messaging/documentation/ZendeskSDKMessaging/UserColors/init(onPrimary:onMessage:onAction:)":{"url":"\/documentation\/zendesksdkmessaging\/usercolors\/init(onprimary:onmessage:onaction:)","kind":"symbol","identifier":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/UserColors\/init(onPrimary:onMessage:onAction:)","type":"topic","role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"initOnPrimary:onMessage:onAction:"}],"title":"init(onPrimary:onMessage:onAction:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"onPrimary"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"text":"?, ","kind":"text"},{"text":"onMessage","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"onAction"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"text":"?)","kind":"text"}]},"doc://com.zendesk.Messaging/SH":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.Messaging\/SH","title":"Swift.Hashable"},"doc://com.zendesk.Messaging/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.Messaging\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.zendesk.Messaging/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.Messaging\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.zendesk.Messaging/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.Messaging\/objc(cs)NSObject","title":"NSObject"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"ZDKUserColors"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"ZDKUserColors","kind":"identifier"}]},{"op":"replace","value":[{"text":"ZDKUserColors","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/UserColors\/init(onPrimary:onMessage:onAction:)"]}],"path":"\/topicSections"},{"value":[{"kind":"relationships","identifiers":["doc:\/\/com.zendesk.Messaging\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From"}],"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKUserColors"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1UserColors\/title","value":"ZDKUserColors"},{"path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1UserColors\/fragments","value":[{"kind":"identifier","text":"ZDKUserColors"}],"op":"replace"},{"op":"replace","value":"initOnPrimary:onMessage:onAction:","path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1UserColors~1init(onPrimary:onMessage:onAction:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1UserColors~1init(onPrimary:onMessage:onAction:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initOnPrimary:onMessage:onAction:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}