{"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"handleTap"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"userInfo","kind":"internalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"], ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The push notification payload."}],"type":"paragraph"}],"name":"userInfo"},{"content":[{"inlineContent":[{"type":"text","text":"An optional "},{"type":"codeVoice","code":"UIViewController"},{"type":"text","text":"  instance."}],"type":"paragraph"}],"name":"completion"}],"kind":"parameters"},{"kind":"content","content":[{"anchor":"discussion","text":"Discussion","level":2,"type":"heading"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"text":"The completion is called on the main thread.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If "},{"type":"codeVoice","code":"Messaging"},{"text":" is not initialized the completion will return nil.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If "},{"type":"codeVoice","code":"Messaging"},{"type":"text","text":" is in the process of being initialized this method will wait, and then a "},{"type":"codeVoice","code":"UIViewController"},{"type":"text","text":" will be returned."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If "},{"code":"Messaging","type":"codeVoice"},{"text":" has been initialized a ","type":"text"},{"type":"codeVoice","code":"UIViewController"},{"type":"text","text":" will be returned."}]}]}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkmessaging\/pushnotifications\/handletap(_:completion:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkmessaging\/pushnotifications\/handletap(_:completion:)"]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging","doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/PushNotifications"]]},"abstract":[{"type":"text","text":"Handles the tap of a push notification if the payload belongs to "},{"type":"codeVoice","code":"Messaging"},{"text":".","type":"text"}],"sections":[],"identifier":{"url":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/PushNotifications\/handleTap(_:completion:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"modules":[{"name":"ZendeskSDKMessaging"}],"roleHeading":"Type Method","externalID":"c:@M@ZendeskSDKMessaging@objc(cs)ZDKPushNotifications(cm)handleTap:completion:","symbolKind":"method","role":"symbol","title":"handleTap(_:completion:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"handleTap"},{"text":"([","kind":"text"},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"navigatorTitle":[{"text":"handleTap:completion:","kind":"identifier"}]},"references":{"doc://com.zendesk.Messaging/documentation/ZendeskSDKMessaging/PushNotifications/handleTap(_:completion:)":{"url":"\/documentation\/zendesksdkmessaging\/pushnotifications\/handletap(_:completion:)","identifier":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/PushNotifications\/handleTap(_:completion:)","abstract":[{"type":"text","text":"Handles the tap of a push notification if the payload belongs to "},{"type":"codeVoice","code":"Messaging"},{"type":"text","text":"."}],"kind":"symbol","title":"handleTap(_:completion:)","type":"topic","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"handleTap","kind":"identifier"},{"text":"([","kind":"text"},{"text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"], ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"navigatorTitle":[{"text":"handleTap:completion:","kind":"identifier"}]},"doc://com.zendesk.Messaging/documentation/ZendeskSDKMessaging":{"title":"ZendeskSDKMessaging","abstract":[],"url":"\/documentation\/zendesksdkmessaging","identifier":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging","role":"collection","type":"topic","kind":"symbol"},"doc://com.zendesk.Messaging/documentation/ZendeskSDKMessaging/PushNotifications":{"title":"PushNotifications","abstract":[{"type":"text","text":"The entry point to execute push notification related SDK actions."},{"type":"text","text":" "},{"text":"Register device token with ","type":"text"},{"type":"codeVoice","code":"PushNotifications.updatePushNotificationToken(:)"},{"text":".","type":"text"}],"url":"\/documentation\/zendesksdkmessaging\/pushnotifications","identifier":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/PushNotifications","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PushNotifications","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PushNotifications"}],"role":"symbol","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"path":"\/metadata\/title","op":"replace","value":"handleTap:completion:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"handleTap:completion:","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"handleTap:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSDictionary","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDictionary"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"userInfo"},{"text":" ","kind":"text"},{"text":"completion:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"void (^)(UIViewController *)","preciseIdentifier":"c:BFv(#*$objc(cs)UIViewController)","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"handleTap:completion:","op":"replace","path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1PushNotifications~1handleTap(_:completion:)\/title"},{"path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1PushNotifications~1handleTap(_:completion:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"handleTap:completion:","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"ZDKPushNotifications","path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1PushNotifications\/title"},{"value":[{"kind":"identifier","text":"ZDKPushNotifications"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1PushNotifications\/fragments"}]}]}