{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/UserColors\/init(onPrimary:onMessage:onAction:)"},"metadata":{"symbolKind":"init","title":"init(onPrimary:onMessage:onAction:)","modules":[{"name":"ZendeskSDKMessaging"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"onPrimary","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"onMessage","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"onAction","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"text":"?)","kind":"text"}],"externalID":"c:@M@ZendeskSDKMessaging@objc(cs)ZDKUserColors(im)initOnPrimary:onMessage:onAction:","navigatorTitle":[{"kind":"identifier","text":"initOnPrimary:onMessage:onAction:"}],"roleHeading":"Initializer","role":"symbol"},"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"text":"onPrimary","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"onMessage","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"onAction"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/zendesksdkmessaging\/usercolors\/init(onprimary:onmessage:onaction:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdkmessaging\/usercolors\/init(onprimary:onmessage:onaction:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging","doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/UserColors"]]},"references":{"doc://com.zendesk.Messaging/documentation/ZendeskSDKMessaging/UserColors":{"type":"topic","role":"symbol","url":"\/documentation\/zendesksdkmessaging\/usercolors","identifier":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/UserColors","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserColors"}],"navigatorTitle":[{"kind":"identifier","text":"UserColors"}],"abstract":[{"text":"Model that contains the colors provided by the user to be used in the SDK.","type":"text"}],"kind":"symbol","title":"UserColors"},"doc://com.zendesk.Messaging/documentation/ZendeskSDKMessaging":{"type":"topic","role":"collection","url":"\/documentation\/zendesksdkmessaging","identifier":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging","abstract":[],"kind":"symbol","title":"ZendeskSDKMessaging"},"doc://com.zendesk.Messaging/documentation/ZendeskSDKMessaging/UserColors/init(onPrimary:onMessage:onAction:)":{"title":"init(onPrimary:onMessage:onAction:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"onPrimary","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"onMessage","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"onAction","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?)"}],"kind":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"initOnPrimary:onMessage:onAction:"}],"url":"\/documentation\/zendesksdkmessaging\/usercolors\/init(onprimary:onmessage:onaction:)","identifier":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/UserColors\/init(onPrimary:onMessage:onAction:)","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"initOnPrimary:onMessage:onAction:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"initOnPrimary:onMessage:onAction:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"kind":"identifier","text":"initOnPrimary:"},{"text":"(","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":" *) "},{"text":"onPrimary","kind":"internalParam"},{"kind":"text","text":" "},{"text":"onMessage:","kind":"identifier"},{"kind":"text","text":"("},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":" *) ","kind":"text"},{"text":"onMessage","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onAction:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"kind":"text","text":" *) "},{"text":"onAction","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1UserColors\/title","value":"ZDKUserColors"},{"path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1UserColors\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKUserColors"}]},{"path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1UserColors~1init(onPrimary:onMessage:onAction:)\/title","op":"replace","value":"initOnPrimary:onMessage:onAction:"},{"value":[{"text":"- ","kind":"text"},{"text":"initOnPrimary:onMessage:onAction:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1UserColors~1init(onPrimary:onMessage:onAction:)\/fragments","op":"replace"}]}]}