{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"messagingShouldNotDisplay"}],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/zendesksdkmessaging\/pushresponsibility\/messagingshouldnotdisplay"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkmessaging\/pushresponsibility\/messagingshouldnotdisplay"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"metadata":{"navigatorTitle":[{"text":"ZDKPushResponsibilityMessagingShouldNotDisplay","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"messagingShouldNotDisplay","kind":"identifier"}],"role":"symbol","roleHeading":"Case","symbolKind":"case","modules":[{"name":"ZendeskSDKMessaging"}],"title":"PushResponsibility.messagingShouldNotDisplay","externalID":"c:@M@ZendeskSDKMessaging@E@ZDKPushResponsibility@ZDKPushResponsibilityMessagingShouldNotDisplay"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging","doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/PushResponsibility"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/PushResponsibility\/messagingShouldNotDisplay"},"kind":"symbol","abstract":[{"text":"The payload is from ","type":"text"},{"type":"codeVoice","code":"Messaging"},{"type":"text","text":" but the SDK will not display it"},{"text":" ","type":"text"},{"text":"because the conversation screen is currently visible to the user.","type":"text"}],"references":{"doc://com.zendesk.Messaging/documentation/ZendeskSDKMessaging/PushResponsibility":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PushResponsibility"}],"navigatorTitle":[{"kind":"identifier","text":"PushResponsibility"}],"identifier":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/PushResponsibility","kind":"symbol","type":"topic","url":"\/documentation\/zendesksdkmessaging\/pushresponsibility","role":"symbol","title":"PushResponsibility","abstract":[{"text":"Represents whether a push notification payload belongs to ","type":"text"},{"type":"codeVoice","code":"Messaging"},{"text":",","type":"text"},{"type":"text","text":" "},{"text":"and if the SDK is in a state in which the notification should be displayed.","type":"text"}]},"doc://com.zendesk.Messaging/documentation/ZendeskSDKMessaging":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging","abstract":[],"url":"\/documentation\/zendesksdkmessaging","title":"ZendeskSDKMessaging","role":"collection"},"doc://com.zendesk.Messaging/documentation/ZendeskSDKMessaging/PushResponsibility/messagingShouldNotDisplay":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"messagingShouldNotDisplay"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKPushResponsibilityMessagingShouldNotDisplay"}],"identifier":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/PushResponsibility\/messagingShouldNotDisplay","kind":"symbol","type":"topic","url":"\/documentation\/zendesksdkmessaging\/pushresponsibility\/messagingshouldnotdisplay","role":"symbol","title":"PushResponsibility.messagingShouldNotDisplay","abstract":[{"type":"text","text":"The payload is from "},{"type":"codeVoice","code":"Messaging"},{"text":" but the SDK will not display it","type":"text"},{"text":" ","type":"text"},{"text":"because the conversation screen is currently visible to the user.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"ZDKPushResponsibilityMessagingShouldNotDisplay","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKPushResponsibilityMessagingShouldNotDisplay"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"ZDKPushResponsibilityMessagingShouldNotDisplay","kind":"identifier"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"ZDKPushResponsibility","op":"replace","path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1PushResponsibility\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1PushResponsibility\/fragments","value":[{"kind":"identifier","text":"ZDKPushResponsibility"}]},{"op":"replace","value":"ZDKPushResponsibilityMessagingShouldNotDisplay","path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1PushResponsibility~1messagingShouldNotDisplay\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1PushResponsibility~1messagingShouldNotDisplay\/fragments","value":[{"text":"ZDKPushResponsibilityMessagingShouldNotDisplay","kind":"identifier"}]}]}]}