{"hierarchy":{"paths":[["doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging","doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/PushNotifications"]]},"identifier":{"url":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/PushNotifications\/updatePushNotificationToken(_:)","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/zendesksdkmessaging\/pushnotifications\/updatepushnotificationtoken(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkmessaging\/pushnotifications\/updatepushnotificationtoken(_:)"]}],"metadata":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"updatePushNotificationToken","kind":"identifier"},{"kind":"text","text":"("},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":")","kind":"text"}],"roleHeading":"Type Method","title":"updatePushNotificationToken(_:)","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"updatePushNotificationToken:"}],"role":"symbol","modules":[{"name":"ZendeskSDKMessaging"}],"externalID":"c:@M@ZendeskSDKMessaging@objc(cs)ZDKPushNotifications(cm)updatePushNotificationToken:"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"updatePushNotificationToken"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"token"},{"kind":"text","text":": "},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The token to be sent to the server."}]}],"name":"token"}]},{"kind":"content","content":[{"level":2,"type":"heading","text":"Discussion","anchor":"discussion"},{"style":"note","type":"aside","name":"Note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If "},{"type":"codeVoice","code":"Messaging"},{"type":"text","text":" is initialized and a "},{"code":"User","type":"codeVoice"},{"type":"text","text":" exists an attempt will be made to update the token."},{"type":"text","text":" "},{"text":"Otherwise the token will be stored for when these become available.","type":"text"}]}]}]}],"abstract":[{"text":"Update a push token to receive push notifications.","type":"text"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://com.zendesk.Messaging/documentation/ZendeskSDKMessaging/PushNotifications/updatePushNotificationToken(_:)":{"type":"topic","identifier":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/PushNotifications\/updatePushNotificationToken(_:)","url":"\/documentation\/zendesksdkmessaging\/pushnotifications\/updatepushnotificationtoken(_:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"updatePushNotificationToken"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"text":")","kind":"text"}],"abstract":[{"text":"Update a push token to receive push notifications.","type":"text"}],"kind":"symbol","role":"symbol","title":"updatePushNotificationToken(_:)","navigatorTitle":[{"text":"updatePushNotificationToken:","kind":"identifier"}]},"doc://com.zendesk.Messaging/documentation/ZendeskSDKMessaging/PushNotifications":{"identifier":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/PushNotifications","type":"topic","url":"\/documentation\/zendesksdkmessaging\/pushnotifications","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PushNotifications","kind":"identifier"}],"abstract":[{"type":"text","text":"The entry point to execute push notification related SDK actions."},{"text":" ","type":"text"},{"type":"text","text":"Register device token with "},{"type":"codeVoice","code":"PushNotifications.updatePushNotificationToken(:)"},{"type":"text","text":"."}],"kind":"symbol","role":"symbol","title":"PushNotifications","navigatorTitle":[{"text":"PushNotifications","kind":"identifier"}]},"doc://com.zendesk.Messaging/documentation/ZendeskSDKMessaging":{"url":"\/documentation\/zendesksdkmessaging","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging","type":"topic","title":"ZendeskSDKMessaging","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Type Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"updatePushNotificationToken:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"updatePushNotificationToken:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"updatePushNotificationToken:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSData","text":"NSData"},{"text":" *) ","kind":"text"},{"text":"token","kind":"internalParam"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"updatePushNotificationToken:","path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1PushNotifications~1updatePushNotificationToken(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1PushNotifications~1updatePushNotificationToken(_:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"updatePushNotificationToken:"}]},{"value":"ZDKPushNotifications","path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1PushNotifications\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1PushNotifications\/fragments","value":[{"text":"ZDKPushNotifications","kind":"identifier"}],"op":"replace"}]}]}