{"kind":"symbol","metadata":{"symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"ZDKPushResponsibilityMessagingShouldDisplay"}],"externalID":"c:@M@ZendeskSDKMessaging@E@ZDKPushResponsibility@ZDKPushResponsibilityMessagingShouldDisplay","title":"PushResponsibility.messagingShouldDisplay","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"messagingShouldDisplay"}],"roleHeading":"Case","modules":[{"name":"ZendeskSDKMessaging"}]},"abstract":[{"type":"text","text":"The payload is from "},{"code":"Messaging","type":"codeVoice"},{"type":"text","text":" and the SDK can display it."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/PushResponsibility\/messagingShouldDisplay"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging","doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/PushResponsibility"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"messagingShouldDisplay"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/zendesksdkmessaging\/pushresponsibility\/messagingshoulddisplay"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdkmessaging\/pushresponsibility\/messagingshoulddisplay"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://com.zendesk.Messaging/documentation/ZendeskSDKMessaging/PushResponsibility/messagingShouldDisplay":{"url":"\/documentation\/zendesksdkmessaging\/pushresponsibility\/messagingshoulddisplay","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"messagingShouldDisplay","kind":"identifier"}],"title":"PushResponsibility.messagingShouldDisplay","type":"topic","abstract":[{"text":"The payload is from ","type":"text"},{"type":"codeVoice","code":"Messaging"},{"text":" and the SDK can display it.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"ZDKPushResponsibilityMessagingShouldDisplay","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/PushResponsibility\/messagingShouldDisplay","kind":"symbol"},"doc://com.zendesk.Messaging/documentation/ZendeskSDKMessaging/PushResponsibility":{"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PushResponsibility","kind":"identifier"}],"navigatorTitle":[{"text":"PushResponsibility","kind":"identifier"}],"title":"PushResponsibility","url":"\/documentation\/zendesksdkmessaging\/pushresponsibility","identifier":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/PushResponsibility","role":"symbol","abstract":[{"text":"Represents whether a push notification payload belongs to ","type":"text"},{"type":"codeVoice","code":"Messaging"},{"text":",","type":"text"},{"text":" ","type":"text"},{"text":"and if the SDK is in a state in which the notification should be displayed.","type":"text"}],"kind":"symbol"},"doc://com.zendesk.Messaging/documentation/ZendeskSDKMessaging":{"identifier":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging","kind":"symbol","url":"\/documentation\/zendesksdkmessaging","role":"collection","title":"ZendeskSDKMessaging","type":"topic","abstract":[]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"ZDKPushResponsibilityMessagingShouldDisplay","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"ZDKPushResponsibilityMessagingShouldDisplay"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"ZDKPushResponsibilityMessagingShouldDisplay","kind":"identifier"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"ZDKPushResponsibilityMessagingShouldDisplay","op":"replace","path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1PushResponsibility~1messagingShouldDisplay\/title"},{"value":[{"kind":"identifier","text":"ZDKPushResponsibilityMessagingShouldDisplay"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1PushResponsibility~1messagingShouldDisplay\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1PushResponsibility\/title","value":"ZDKPushResponsibility"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1PushResponsibility\/fragments","value":[{"text":"ZDKPushResponsibility","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1PushResponsibility\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKPushResponsibility"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}