{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/NativeMessagingSDKVersionString"},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkmessaging\/nativemessagingsdkversionstring"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkmessaging\/nativemessagingsdkversionstring"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"NativeMessagingSDKVersionString","kind":"identifier"},{"text":": <<error type>>","kind":"text"}],"languages":["swift"]}]}],"metadata":{"role":"symbol","externalID":"c:@NativeMessagingSDKVersionString","roleHeading":"Global Variable","modules":[{"name":"ZendeskSDKMessaging"}],"navigatorTitle":[{"kind":"identifier","text":"NativeMessagingSDKVersionString"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"NativeMessagingSDKVersionString"},{"kind":"text","text":": <<error type>>"}],"title":"NativeMessagingSDKVersionString","symbolKind":"var"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging"]]},"abstract":[{"text":"Project version string for NativeMessagingSDK.","type":"text"}],"references":{"doc://com.zendesk.Messaging/documentation/ZendeskSDKMessaging/NativeMessagingSDKVersionString":{"navigatorTitle":[{"kind":"identifier","text":"NativeMessagingSDKVersionString"}],"role":"symbol","abstract":[{"type":"text","text":"Project version string for NativeMessagingSDK."}],"type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NativeMessagingSDKVersionString","kind":"identifier"},{"kind":"text","text":": <<error type>>"}],"title":"NativeMessagingSDKVersionString","kind":"symbol","url":"\/documentation\/zendesksdkmessaging\/nativemessagingsdkversionstring","identifier":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/NativeMessagingSDKVersionString"},"doc://com.zendesk.Messaging/documentation/ZendeskSDKMessaging":{"url":"\/documentation\/zendesksdkmessaging","role":"collection","identifier":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging","title":"ZendeskSDKMessaging","kind":"symbol","abstract":[],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Global Variable","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"NativeMessagingSDKVersionString"},{"value":"var","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"NativeMessagingSDKVersionString"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:c","text":"unsigned char"},{"kind":"text","text":" "},{"text":"NativeMessagingSDKVersionString","kind":"identifier"},{"kind":"text","text":"[]"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1NativeMessagingSDKVersionString\/title","op":"replace","value":"NativeMessagingSDKVersionString"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1NativeMessagingSDKVersionString\/fragments","value":[{"kind":"identifier","text":"NativeMessagingSDKVersionString"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}