{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkmessaging\/pushresponsibility"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkmessaging\/pushresponsibility"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"kind":"symbol","metadata":{"symbolKind":"enum","externalID":"c:@M@ZendeskSDKMessaging@E@ZDKPushResponsibility","role":"symbol","roleHeading":"Enumeration","modules":[{"name":"ZendeskSDKMessaging"}],"title":"PushResponsibility","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PushResponsibility"}],"navigatorTitle":[{"text":"PushResponsibility","kind":"identifier"}]},"topicSections":[{"identifiers":["doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/PushResponsibility\/messagingShouldDisplay","doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/PushResponsibility\/messagingShouldNotDisplay","doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/PushResponsibility\/notFromMessaging"],"title":"Enumeration Cases"},{"title":"Initializers","identifiers":["doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/PushResponsibility\/init(rawValue:)"]},{"identifiers":["doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/PushResponsibility\/Equatable-Implementations","doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/PushResponsibility\/RawRepresentable-Implementations"],"generated":true,"title":"Default Implementations"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(ZDKPushResponsibility) ","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PushResponsibility"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging"]]},"identifier":{"url":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/PushResponsibility","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Represents whether a push notification payload belongs to "},{"type":"codeVoice","code":"Messaging"},{"type":"text","text":","},{"type":"text","text":" "},{"type":"text","text":"and if the SDK is in a state in which the notification should be displayed."}],"relationshipsSections":[{"type":"conformsTo","identifiers":["doc:\/\/com.zendesk.Messaging\/SQ","doc:\/\/com.zendesk.Messaging\/SH","doc:\/\/com.zendesk.Messaging\/SY"],"title":"Conforms To","kind":"relationships"}],"references":{"doc://com.zendesk.Messaging/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.zendesk.Messaging\/SY"},"doc://com.zendesk.Messaging/documentation/ZendeskSDKMessaging/PushResponsibility/Equatable-Implementations":{"role":"collectionGroup","identifier":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/PushResponsibility\/Equatable-Implementations","url":"\/documentation\/zendesksdkmessaging\/pushresponsibility\/equatable-implementations","type":"topic","abstract":[],"title":"Equatable Implementations","kind":"article"},"doc://com.zendesk.Messaging/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.zendesk.Messaging\/SH"},"doc://com.zendesk.Messaging/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.zendesk.Messaging\/SQ"},"doc://com.zendesk.Messaging/documentation/ZendeskSDKMessaging/PushResponsibility/messagingShouldDisplay":{"kind":"symbol","abstract":[{"text":"The payload is from ","type":"text"},{"code":"Messaging","type":"codeVoice"},{"text":" and the SDK can display it.","type":"text"}],"identifier":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/PushResponsibility\/messagingShouldDisplay","type":"topic","title":"PushResponsibility.messagingShouldDisplay","url":"\/documentation\/zendesksdkmessaging\/pushresponsibility\/messagingshoulddisplay","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"messagingShouldDisplay","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKPushResponsibilityMessagingShouldDisplay"}]},"doc://com.zendesk.Messaging/documentation/ZendeskSDKMessaging":{"url":"\/documentation\/zendesksdkmessaging","role":"collection","identifier":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging","title":"ZendeskSDKMessaging","kind":"symbol","abstract":[],"type":"topic"},"doc://com.zendesk.Messaging/documentation/ZendeskSDKMessaging/PushResponsibility/init(rawValue:)":{"type":"topic","identifier":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/PushResponsibility\/init(rawValue:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"title":"init(rawValue:)","url":"\/documentation\/zendesksdkmessaging\/pushresponsibility\/init(rawvalue:)","abstract":[],"role":"symbol","kind":"symbol"},"doc://com.zendesk.Messaging/documentation/ZendeskSDKMessaging/PushResponsibility":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"PushResponsibility","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/PushResponsibility","url":"\/documentation\/zendesksdkmessaging\/pushresponsibility","navigatorTitle":[{"kind":"identifier","text":"PushResponsibility"}],"kind":"symbol","title":"PushResponsibility","abstract":[{"type":"text","text":"Represents whether a push notification payload belongs to "},{"code":"Messaging","type":"codeVoice"},{"type":"text","text":","},{"text":" ","type":"text"},{"text":"and if the SDK is in a state in which the notification should be displayed.","type":"text"}],"type":"topic","role":"symbol"},"doc://com.zendesk.Messaging/documentation/ZendeskSDKMessaging/PushResponsibility/notFromMessaging":{"url":"\/documentation\/zendesksdkmessaging\/pushresponsibility\/notfrommessaging","kind":"symbol","abstract":[{"type":"text","text":"The payload is not from "},{"type":"codeVoice","code":"Messaging"},{"type":"text","text":" and can’t be handled by the SDK."}],"role":"symbol","title":"PushResponsibility.notFromMessaging","identifier":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/PushResponsibility\/notFromMessaging","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"notFromMessaging","kind":"identifier"}],"navigatorTitle":[{"text":"ZDKPushResponsibilityNotFromMessaging","kind":"identifier"}]},"doc://com.zendesk.Messaging/documentation/ZendeskSDKMessaging/PushResponsibility/RawRepresentable-Implementations":{"abstract":[],"kind":"article","identifier":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/PushResponsibility\/RawRepresentable-Implementations","title":"RawRepresentable Implementations","type":"topic","url":"\/documentation\/zendesksdkmessaging\/pushresponsibility\/rawrepresentable-implementations","role":"collectionGroup"},"doc://com.zendesk.Messaging/documentation/ZendeskSDKMessaging/PushResponsibility/messagingShouldNotDisplay":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/PushResponsibility\/messagingShouldNotDisplay","title":"PushResponsibility.messagingShouldNotDisplay","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"messagingShouldNotDisplay","kind":"identifier"}],"abstract":[{"text":"The payload is from ","type":"text"},{"type":"codeVoice","code":"Messaging"},{"type":"text","text":" but the SDK will not display it"},{"type":"text","text":" "},{"type":"text","text":"because the conversation screen is currently visible to the user."}],"url":"\/documentation\/zendesksdkmessaging\/pushresponsibility\/messagingshouldnotdisplay","navigatorTitle":[{"kind":"identifier","text":"ZDKPushResponsibilityMessagingShouldNotDisplay"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"ZDKPushResponsibility"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"value":[{"kind":"identifier","text":"ZDKPushResponsibility"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKPushResponsibility"}],"path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/PushResponsibility\/messagingShouldDisplay","doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/PushResponsibility\/messagingShouldNotDisplay","doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/PushResponsibility\/notFromMessaging"],"title":"Enumeration Cases"}]},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"ZDKPushResponsibility","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1PushResponsibility~1messagingShouldDisplay\/title","op":"replace","value":"ZDKPushResponsibilityMessagingShouldDisplay"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1PushResponsibility~1messagingShouldDisplay\/fragments","value":[{"kind":"identifier","text":"ZDKPushResponsibilityMessagingShouldDisplay"}]},{"path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1PushResponsibility\/title","value":"ZDKPushResponsibility","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1PushResponsibility\/fragments","value":[{"text":"ZDKPushResponsibility","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1PushResponsibility~1notFromMessaging\/title","value":"ZDKPushResponsibilityNotFromMessaging"},{"path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1PushResponsibility~1notFromMessaging\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKPushResponsibilityNotFromMessaging"}]},{"path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1PushResponsibility~1messagingShouldNotDisplay\/title","op":"replace","value":"ZDKPushResponsibilityMessagingShouldNotDisplay"},{"value":[{"text":"ZDKPushResponsibilityMessagingShouldNotDisplay","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1PushResponsibility~1messagingShouldNotDisplay\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}