{"hierarchy":{"paths":[["doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging","doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/PushResponsibility"]]},"identifier":{"url":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/PushResponsibility\/notFromMessaging","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkmessaging\/pushresponsibility\/notfrommessaging"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkmessaging\/pushresponsibility\/notfrommessaging"]}],"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"notFromMessaging"}],"symbolKind":"case","roleHeading":"Case","modules":[{"name":"ZendeskSDKMessaging"}],"title":"PushResponsibility.notFromMessaging","externalID":"c:@M@ZendeskSDKMessaging@E@ZDKPushResponsibility@ZDKPushResponsibilityNotFromMessaging","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDKPushResponsibilityNotFromMessaging"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notFromMessaging"}]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"The payload is not from "},{"code":"Messaging","type":"codeVoice"},{"text":" and can’t be handled by the SDK.","type":"text"}],"references":{"doc://com.zendesk.Messaging/documentation/ZendeskSDKMessaging":{"title":"ZendeskSDKMessaging","role":"collection","abstract":[],"identifier":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging","type":"topic","kind":"symbol","url":"\/documentation\/zendesksdkmessaging"},"doc://com.zendesk.Messaging/documentation/ZendeskSDKMessaging/PushResponsibility/notFromMessaging":{"kind":"symbol","url":"\/documentation\/zendesksdkmessaging\/pushresponsibility\/notfrommessaging","navigatorTitle":[{"kind":"identifier","text":"ZDKPushResponsibilityNotFromMessaging"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"notFromMessaging"}],"title":"PushResponsibility.notFromMessaging","type":"topic","identifier":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/PushResponsibility\/notFromMessaging","role":"symbol","abstract":[{"text":"The payload is not from ","type":"text"},{"code":"Messaging","type":"codeVoice"},{"type":"text","text":" and can’t be handled by the SDK."}]},"doc://com.zendesk.Messaging/documentation/ZendeskSDKMessaging/PushResponsibility":{"abstract":[{"text":"Represents whether a push notification payload belongs to ","type":"text"},{"code":"Messaging","type":"codeVoice"},{"type":"text","text":","},{"text":" ","type":"text"},{"text":"and if the SDK is in a state in which the notification should be displayed.","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"PushResponsibility","kind":"identifier"}],"title":"PushResponsibility","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PushResponsibility"}],"identifier":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/PushResponsibility","type":"topic","kind":"symbol","url":"\/documentation\/zendesksdkmessaging\/pushresponsibility"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"ZDKPushResponsibilityNotFromMessaging"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"ZDKPushResponsibilityNotFromMessaging","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"ZDKPushResponsibilityNotFromMessaging"}]}]},"op":"replace"},{"value":"ZDKPushResponsibilityNotFromMessaging","path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1PushResponsibility~1notFromMessaging\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1PushResponsibility~1notFromMessaging\/fragments","value":[{"kind":"identifier","text":"ZDKPushResponsibilityNotFromMessaging"}]},{"value":"ZDKPushResponsibility","path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1PushResponsibility\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1PushResponsibility\/fragments","op":"replace","value":[{"text":"ZDKPushResponsibility","kind":"identifier"}]}]}]}