{"metadata":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"userLightColors","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UserColors","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKMessaging@objc(cs)ZDKUserColors"},{"text":")","kind":"text"}],"externalID":"c:@M@ZendeskSDKMessaging@objc(cs)ZDKDefaultMessagingFactory(im)initWithUserLightColors:","symbolKind":"init","modules":[{"name":"ZendeskSDKMessaging"}],"navigatorTitle":[{"text":"initWithUserLightColors:","kind":"identifier"}],"roleHeading":"Initializer","role":"symbol","title":"init(userLightColors:)"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"userLightColors","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/UserColors","preciseIdentifier":"c:@M@ZendeskSDKMessaging@objc(cs)ZDKUserColors","text":"UserColors","kind":"typeIdentifier"},{"text":")","kind":"text"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Object that contains the light colors provided by the user to be used in the SDK.","type":"text"}]}],"name":"userLightColors"}]}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging","doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/DefaultMessagingFactory"]]},"variants":[{"paths":["\/documentation\/zendesksdkmessaging\/defaultmessagingfactory\/init(userlightcolors:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdkmessaging\/defaultmessagingfactory\/init(userlightcolors:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/DefaultMessagingFactory\/init(userLightColors:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"text":"Default initialization of ","type":"text"},{"code":"MessagingFactory","type":"codeVoice"}],"references":{"doc://com.zendesk.Messaging/documentation/ZendeskSDKMessaging":{"url":"\/documentation\/zendesksdkmessaging","title":"ZendeskSDKMessaging","type":"topic","kind":"symbol","identifier":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging","abstract":[],"role":"collection"},"doc://com.zendesk.Messaging/documentation/ZendeskSDKMessaging/DefaultMessagingFactory/init(userLightColors:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"userLightColors","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskSDKMessaging@objc(cs)ZDKUserColors","text":"UserColors","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithUserLightColors:","kind":"identifier"}],"role":"symbol","url":"\/documentation\/zendesksdkmessaging\/defaultmessagingfactory\/init(userlightcolors:)","kind":"symbol","title":"init(userLightColors:)","type":"topic","abstract":[{"type":"text","text":"Default initialization of "},{"type":"codeVoice","code":"MessagingFactory"}],"identifier":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/DefaultMessagingFactory\/init(userLightColors:)"},"doc://com.zendesk.Messaging/documentation/ZendeskSDKMessaging/DefaultMessagingFactory":{"url":"\/documentation\/zendesksdkmessaging\/defaultmessagingfactory","navigatorTitle":[{"text":"DefaultMessagingFactory","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/DefaultMessagingFactory","title":"DefaultMessagingFactory","abstract":[],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DefaultMessagingFactory","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://com.zendesk.Messaging/documentation/ZendeskSDKMessaging/UserColors":{"url":"\/documentation\/zendesksdkmessaging\/usercolors","title":"UserColors","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserColors"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/UserColors","abstract":[{"type":"text","text":"Model that contains the colors provided by the user to be used in the SDK."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"UserColors"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"initWithUserLightColors:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithUserLightColors:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithUserLightColors:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/UserColors","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskSDKMessaging@objc(cs)ZDKUserColors","text":"ZDKUserColors"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"userLightColors"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"parameters":[{"content":[{"inlineContent":[{"text":"Object that contains the light colors provided by the user to be used in the SDK.","type":"text"}],"type":"paragraph"}],"name":"userLightColors"}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"initWithUserLightColors:","op":"replace","path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1DefaultMessagingFactory~1init(userLightColors:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithUserLightColors:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1DefaultMessagingFactory~1init(userLightColors:)\/fragments"},{"value":"ZDKDefaultMessagingFactory","op":"replace","path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1DefaultMessagingFactory\/title"},{"value":[{"kind":"identifier","text":"ZDKDefaultMessagingFactory"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1DefaultMessagingFactory\/fragments"},{"value":[{"text":"ZDKDefaultMessagingFactory","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1DefaultMessagingFactory\/navigatorTitle"},{"value":"ZDKUserColors","op":"replace","path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1UserColors\/title"},{"value":[{"text":"ZDKUserColors","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1UserColors\/fragments"},{"value":[{"kind":"identifier","text":"ZDKUserColors"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1UserColors\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}