{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"()","kind":"text"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/zendesksdkmessaging\/defaultmessagingfactory\/init()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendesksdkmessaging\/defaultmessagingfactory\/init()"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging","doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/DefaultMessagingFactory"]]},"metadata":{"symbolKind":"init","modules":[{"name":"ZendeskSDKMessaging"}],"role":"symbol","externalID":"c:@M@ZendeskSDKMessaging@objc(cs)ZDKDefaultMessagingFactory(im)init","title":"init()","navigatorTitle":[{"kind":"identifier","text":"init"}],"roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}]},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/DefaultMessagingFactory\/init()","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://com.zendesk.Messaging/documentation/ZendeskSDKMessaging/DefaultMessagingFactory/init()":{"url":"\/documentation\/zendesksdkmessaging\/defaultmessagingfactory\/init()","role":"symbol","type":"topic","kind":"symbol","title":"init()","fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/DefaultMessagingFactory\/init()","navigatorTitle":[{"text":"init","kind":"identifier"}]},"doc://com.zendesk.Messaging/documentation/ZendeskSDKMessaging":{"identifier":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging","role":"collection","type":"topic","title":"ZendeskSDKMessaging","url":"\/documentation\/zendesksdkmessaging","abstract":[],"kind":"symbol"},"doc://com.zendesk.Messaging/documentation/ZendeskSDKMessaging/DefaultMessagingFactory":{"abstract":[],"identifier":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/DefaultMessagingFactory","url":"\/documentation\/zendesksdkmessaging\/defaultmessagingfactory","title":"DefaultMessagingFactory","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DefaultMessagingFactory","kind":"identifier"}],"navigatorTitle":[{"text":"DefaultMessagingFactory","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"init","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"init","path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1DefaultMessagingFactory~1init()\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1DefaultMessagingFactory~1init()\/fragments"},{"op":"replace","value":"ZDKDefaultMessagingFactory","path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1DefaultMessagingFactory\/title"},{"op":"replace","value":[{"text":"ZDKDefaultMessagingFactory","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1DefaultMessagingFactory\/fragments"},{"op":"replace","value":[{"text":"ZDKDefaultMessagingFactory","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1DefaultMessagingFactory\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}