{"sections":[],"identifier":{"url":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/PushNotifications","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(ZDKPushNotifications) ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushNotifications"}],"languages":["swift"]}]}],"metadata":{"externalID":"c:@M@ZendeskSDKMessaging@objc(cs)ZDKPushNotifications","symbolKind":"class","role":"symbol","modules":[{"name":"ZendeskSDKMessaging"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PushNotifications"}],"navigatorTitle":[{"text":"PushNotifications","kind":"identifier"}],"title":"PushNotifications","roleHeading":"Class"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendesksdkmessaging\/pushnotifications"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendesksdkmessaging\/pushnotifications"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"text":"The entry point to execute push notification related SDK actions.","type":"text"},{"type":"text","text":" "},{"text":"Register device token with ","type":"text"},{"type":"codeVoice","code":"PushNotifications.updatePushNotificationToken(:)"},{"text":".","type":"text"}],"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.zendesk.Messaging\/objc(cs)NSObject"],"kind":"relationships"},{"kind":"relationships","identifiers":["doc:\/\/com.zendesk.Messaging\/objc(pl)NSObject","doc:\/\/com.zendesk.Messaging\/s7CVarArgP","doc:\/\/com.zendesk.Messaging\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.Messaging\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.Messaging\/SQ","doc:\/\/com.zendesk.Messaging\/SH"],"type":"conformsTo","title":"Conforms To"}],"topicSections":[{"identifiers":["doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/PushNotifications\/handleTap(_:completion:)","doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/PushNotifications\/shouldBeDisplayed(_:)","doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/PushNotifications\/updatePushNotificationToken(_:)"],"title":"Type Methods"}],"kind":"symbol","references":{"doc://com.zendesk.Messaging/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.Messaging\/SQ","title":"Swift.Equatable"},"doc://com.zendesk.Messaging/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.Messaging\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.zendesk.Messaging/documentation/ZendeskSDKMessaging/PushNotifications/updatePushNotificationToken(_:)":{"abstract":[{"type":"text","text":"Update a push token to receive push notifications."}],"url":"\/documentation\/zendesksdkmessaging\/pushnotifications\/updatepushnotificationtoken(_:)","identifier":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/PushNotifications\/updatePushNotificationToken(_:)","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"updatePushNotificationToken","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"},{"kind":"text","text":")"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"updatePushNotificationToken:"}],"title":"updatePushNotificationToken(_:)","kind":"symbol"},"doc://com.zendesk.Messaging/documentation/ZendeskSDKMessaging":{"role":"collection","identifier":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging","kind":"symbol","title":"ZendeskSDKMessaging","abstract":[],"type":"topic","url":"\/documentation\/zendesksdkmessaging"},"doc://com.zendesk.Messaging/documentation/ZendeskSDKMessaging/PushNotifications":{"abstract":[{"type":"text","text":"The entry point to execute push notification related SDK actions."},{"text":" ","type":"text"},{"text":"Register device token with ","type":"text"},{"code":"PushNotifications.updatePushNotificationToken(:)","type":"codeVoice"},{"type":"text","text":"."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PushNotifications","kind":"identifier"}],"type":"topic","title":"PushNotifications","identifier":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/PushNotifications","navigatorTitle":[{"kind":"identifier","text":"PushNotifications"}],"kind":"symbol","url":"\/documentation\/zendesksdkmessaging\/pushnotifications"},"doc://com.zendesk.Messaging/documentation/ZendeskSDKMessaging/PushNotifications/handleTap(_:completion:)":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"handleTap","kind":"identifier"},{"text":"([","kind":"text"},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"text":"], ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": (("},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/PushNotifications\/handleTap(_:completion:)","navigatorTitle":[{"text":"handleTap:completion:","kind":"identifier"}],"kind":"symbol","title":"handleTap(_:completion:)","abstract":[{"text":"Handles the tap of a push notification if the payload belongs to ","type":"text"},{"code":"Messaging","type":"codeVoice"},{"type":"text","text":"."}],"type":"topic","url":"\/documentation\/zendesksdkmessaging\/pushnotifications\/handletap(_:completion:)"},"doc://com.zendesk.Messaging/documentation/ZendeskSDKMessaging/PushNotifications/shouldBeDisplayed(_:)":{"url":"\/documentation\/zendesksdkmessaging\/pushnotifications\/shouldbedisplayed(_:)","title":"shouldBeDisplayed(_:)","identifier":"doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/PushNotifications\/shouldBeDisplayed(_:)","abstract":[{"text":"Check if a push notification payload belongs to ","type":"text"},{"type":"codeVoice","code":"Messaging"},{"type":"text","text":" and can be displayed."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"shouldBeDisplayed"},{"kind":"text","text":"(["},{"text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","text":"PushResponsibility","preciseIdentifier":"c:@M@ZendeskSDKMessaging@E@ZDKPushResponsibility"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"shouldBeDisplayed:"}],"role":"symbol"},"doc://com.zendesk.Messaging/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.Messaging\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.zendesk.Messaging/SH":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.Messaging\/SH","title":"Swift.Hashable"},"doc://com.zendesk.Messaging/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.Messaging\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.zendesk.Messaging/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.Messaging\/objc(cs)NSObject","title":"NSObject"},"doc://com.zendesk.Messaging/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.Messaging\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"ZDKPushNotifications","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"value":[{"text":"ZDKPushNotifications","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"ZDKPushNotifications","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"title":"Type Methods","identifiers":["doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/PushNotifications\/handleTap(_:completion:)","doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/PushNotifications\/shouldBeDisplayed(_:)","doc:\/\/com.zendesk.Messaging\/documentation\/ZendeskSDKMessaging\/PushNotifications\/updatePushNotificationToken(_:)"]}]},{"path":"\/relationshipsSections","op":"replace","value":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.zendesk.Messaging\/objc(cs)NSObject"],"kind":"relationships"}]},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKPushNotifications","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"value":"updatePushNotificationToken:","path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1PushNotifications~1updatePushNotificationToken(_:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1PushNotifications~1updatePushNotificationToken(_:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"updatePushNotificationToken:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1PushNotifications\/title","value":"ZDKPushNotifications","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1PushNotifications\/fragments","value":[{"kind":"identifier","text":"ZDKPushNotifications"}]},{"value":"handleTap:completion:","path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1PushNotifications~1handleTap(_:completion:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1PushNotifications~1handleTap(_:completion:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"handleTap:completion:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1PushNotifications~1shouldBeDisplayed(_:)\/title","value":"shouldBeDisplayed:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.Messaging~1documentation~1ZendeskSDKMessaging~1PushNotifications~1shouldBeDisplayed(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"shouldBeDisplayed:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}